[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Cameron Swinoga <cameronswinoga@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
rand = "0.7"
arrayvec = "0.4"
palette = "0.4"
lazy_static = "1.3"
num-complex = "0.2"
num-traits = "0.2"
structopt = "0.2"
